name = "DancingQueen"
uuid = "2f81b706-3ccb-4e76-a58a-b4b61a9465e2"
authors = ["Yakir Gagnon <12.yakir@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
